// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "study-SwiftUIStates",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "study-SwiftUIStates",
            targets: ["AppModule"],
            bundleIdentifier: "com.bgsmm.study-SwiftUIStates",
            teamIdentifier: "6S2SA26VAN",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .movieReel),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/sparrowcode/AlertKit", "5.1.9"..<"6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "AlertKit", package: "alertkit")
            ],
            path: "."
        )
    ]
)